package com.inc.fcr.mail;

import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;
class MailControllerTest {

    @Test
    void buildHtml() {

        String firstName = "user";
        long userId = 123;
        String paymentId = "1";

        Map<String, String> testCarMap = Map.of(
                "year", "2006",
                "make", "Ferrari",
                "model", "F430 Spider",
                "vin", "ZFFEW59A260147301",
                "pickUpTime", "4/27/26",
                "dropOffTime", "4/30/26"
        );

        List<Long> reservationIds0 = List.of();
        List<Long> reservationIds1 = List.of((long) 111);
        List<Long> reservationIdsN = List.of((long) 111, (long) 222);
        List<Map<String,String>> cars0 = List.of();
        List<Map<String,String>> cars1 = List.of(testCarMap);
        List<Map<String,String>> carsN = List.of(testCarMap, testCarMap);

        assertAll(
            () -> assertEquals("<div style='font-family: sans-serif; max-width: 600px; margin: auto;'><h2>Reservation Confirmed</h2><p>Hi "+firstName+",</p><p>Your reservation is confirmed. Here are your booking details:</p><table style='width:100%; margin-bottom:16px;'><tr><td style='padding:6px; font-weight:bold;'>User ID</td><td style='padding:6px;'>"+userId+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Payment Reference</td><td style='padding:6px;'>"+paymentId+"</td></tr></table><hr/><p>Thank you for choosing FCR Inc!</p></div>",
                MailController.buildHtml(firstName, userId, paymentId, reservationIds0, cars0), "Mail Controller Build HTML does not match with param types {reservationIds0, cars0}"),
            () -> assertEquals("<div style='font-family: sans-serif; max-width: 600px; margin: auto;'><h2>Reservation Confirmed</h2><p>Hi "+firstName+",</p><p>Your reservation is confirmed. Here are your booking details:</p><table style='width:100%; margin-bottom:16px;'><tr><td style='padding:6px; font-weight:bold;'>User ID</td><td style='padding:6px;'>"+userId+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Payment Reference</td><td style='padding:6px;'>"+paymentId+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Reservation ID(s)</td><td style='padding:6px;'>111</td></tr></table><hr/><p>Thank you for choosing FCR Inc!</p></div>",
                MailController.buildHtml(firstName, userId, paymentId, reservationIds1, cars0), "Mail Controller Build HTML does not match with param types {reservationIds1, cars0}"),
            () -> assertEquals("<div style='font-family: sans-serif; max-width: 600px; margin: auto;'><h2>Reservation Confirmed</h2><p>Hi "+firstName+",</p><p>Your reservation is confirmed. Here are your booking details:</p><table style='width:100%; margin-bottom:16px;'><tr><td style='padding:6px; font-weight:bold;'>User ID</td><td style='padding:6px;'>"+userId+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Payment Reference</td><td style='padding:6px;'>"+paymentId+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Reservation ID(s)</td><td style='padding:6px;'>111, 222</td></tr></table><hr/><p>Thank you for choosing FCR Inc!</p></div>",
                MailController.buildHtml(firstName, userId, paymentId, reservationIdsN, cars0), "Mail Controller Build HTML does not match with param types {reservationIdsN, cars0}"),
            () -> assertEquals("<div style='font-family: sans-serif; max-width: 600px; margin: auto;'><h2>Reservation Confirmed</h2><p>Hi "+firstName+",</p><p>Your reservation is confirmed. Here are your booking details:</p><table style='width:100%; margin-bottom:16px;'><tr><td style='padding:6px; font-weight:bold;'>User ID</td><td style='padding:6px;'>"+userId+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Payment Reference</td><td style='padding:6px;'>"+paymentId+"</td></tr></table><hr/><table style='width:100%; border-collapse: collapse; margin-bottom: 16px;'><tr><td style='padding:6px; font-weight:bold;'>Vehicle</td><td style='padding:6px;'>"+testCarMap.get("year")+" "+testCarMap.get("make")+" "+testCarMap.get("model")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>VIN</td><td style='padding:6px;'>"+testCarMap.get("vin")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Pick-up</td><td style='padding:6px;'>"+testCarMap.get("pickUpTime")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Drop-off</td><td style='padding:6px;'>"+testCarMap.get("dropOffTime")+"</td></tr></table><hr/><p>Thank you for choosing FCR Inc!</p></div>",
                MailController.buildHtml(firstName, userId, paymentId, reservationIds0, cars1), "Mail Controller Build HTML does not match with param types {reservationIds0, cars1}"),
            () -> assertEquals("<div style='font-family: sans-serif; max-width: 600px; margin: auto;'><h2>Reservation Confirmed</h2><p>Hi "+firstName+",</p><p>Your reservation is confirmed. Here are your booking details:</p><table style='width:100%; margin-bottom:16px;'><tr><td style='padding:6px; font-weight:bold;'>User ID</td><td style='padding:6px;'>"+userId+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Payment Reference</td><td style='padding:6px;'>"+paymentId+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Reservation ID(s)</td><td style='padding:6px;'>111</td></tr></table><hr/><table style='width:100%; border-collapse: collapse; margin-bottom: 16px;'><tr><td style='padding:6px; font-weight:bold;'>Vehicle</td><td style='padding:6px;'>"+testCarMap.get("year")+" "+testCarMap.get("make")+" "+testCarMap.get("model")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>VIN</td><td style='padding:6px;'>"+testCarMap.get("vin")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Pick-up</td><td style='padding:6px;'>"+testCarMap.get("pickUpTime")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Drop-off</td><td style='padding:6px;'>"+testCarMap.get("dropOffTime")+"</td></tr></table><hr/><p>Thank you for choosing FCR Inc!</p></div>",
                MailController.buildHtml(firstName, userId, paymentId, reservationIds1, cars1), "Mail Controller Build HTML does not match with param types {reservationIds1, cars1}"),
            () -> assertEquals("<div style='font-family: sans-serif; max-width: 600px; margin: auto;'><h2>Reservation Confirmed</h2><p>Hi "+firstName+",</p><p>Your reservation is confirmed. Here are your booking details:</p><table style='width:100%; margin-bottom:16px;'><tr><td style='padding:6px; font-weight:bold;'>User ID</td><td style='padding:6px;'>"+userId+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Payment Reference</td><td style='padding:6px;'>"+paymentId+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Reservation ID(s)</td><td style='padding:6px;'>111, 222</td></tr></table><hr/><table style='width:100%; border-collapse: collapse; margin-bottom: 16px;'><tr><td style='padding:6px; font-weight:bold;'>Vehicle</td><td style='padding:6px;'>"+testCarMap.get("year")+" "+testCarMap.get("make")+" "+testCarMap.get("model")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>VIN</td><td style='padding:6px;'>"+testCarMap.get("vin")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Pick-up</td><td style='padding:6px;'>"+testCarMap.get("pickUpTime")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Drop-off</td><td style='padding:6px;'>"+testCarMap.get("dropOffTime")+"</td></tr></table><hr/><p>Thank you for choosing FCR Inc!</p></div>",
                MailController.buildHtml(firstName, userId, paymentId, reservationIdsN, cars1), "Mail Controller Build HTML does not match with param types {reservationIdsN, cars1}"),
            () -> assertEquals("<div style='font-family: sans-serif; max-width: 600px; margin: auto;'><h2>Reservation Confirmed</h2><p>Hi "+firstName+",</p><p>Your reservation is confirmed. Here are your booking details:</p><table style='width:100%; margin-bottom:16px;'><tr><td style='padding:6px; font-weight:bold;'>User ID</td><td style='padding:6px;'>"+userId+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Payment Reference</td><td style='padding:6px;'>"+paymentId+"</td></tr></table><hr/><table style='width:100%; border-collapse: collapse; margin-bottom: 16px;'><tr><td style='padding:6px; font-weight:bold;'>Vehicle</td><td style='padding:6px;'>"+testCarMap.get("year")+" "+testCarMap.get("make")+" "+testCarMap.get("model")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>VIN</td><td style='padding:6px;'>"+testCarMap.get("vin")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Pick-up</td><td style='padding:6px;'>"+testCarMap.get("pickUpTime")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Drop-off</td><td style='padding:6px;'>"+testCarMap.get("dropOffTime")+"</td></tr></table><hr/><table style='width:100%; border-collapse: collapse; margin-bottom: 16px;'><tr><td style='padding:6px; font-weight:bold;'>Vehicle</td><td style='padding:6px;'>"+testCarMap.get("year")+" "+testCarMap.get("make")+" "+testCarMap.get("model")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>VIN</td><td style='padding:6px;'>"+testCarMap.get("vin")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Pick-up</td><td style='padding:6px;'>"+testCarMap.get("pickUpTime")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Drop-off</td><td style='padding:6px;'>"+testCarMap.get("dropOffTime")+"</td></tr></table><hr/><p>Thank you for choosing FCR Inc!</p></div>",
                MailController.buildHtml(firstName, userId, paymentId, reservationIds0, carsN), "Mail Controller Build HTML does not match with param types {reservationIds0, carsN}"),
            () -> assertEquals("<div style='font-family: sans-serif; max-width: 600px; margin: auto;'><h2>Reservation Confirmed</h2><p>Hi "+firstName+",</p><p>Your reservation is confirmed. Here are your booking details:</p><table style='width:100%; margin-bottom:16px;'><tr><td style='padding:6px; font-weight:bold;'>User ID</td><td style='padding:6px;'>"+userId+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Payment Reference</td><td style='padding:6px;'>"+paymentId+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Reservation ID(s)</td><td style='padding:6px;'>111</td></tr></table><hr/><table style='width:100%; border-collapse: collapse; margin-bottom: 16px;'><tr><td style='padding:6px; font-weight:bold;'>Vehicle</td><td style='padding:6px;'>"+testCarMap.get("year")+" "+testCarMap.get("make")+" "+testCarMap.get("model")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>VIN</td><td style='padding:6px;'>"+testCarMap.get("vin")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Pick-up</td><td style='padding:6px;'>"+testCarMap.get("pickUpTime")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Drop-off</td><td style='padding:6px;'>"+testCarMap.get("dropOffTime")+"</td></tr></table><hr/><table style='width:100%; border-collapse: collapse; margin-bottom: 16px;'><tr><td style='padding:6px; font-weight:bold;'>Vehicle</td><td style='padding:6px;'>"+testCarMap.get("year")+" "+testCarMap.get("make")+" "+testCarMap.get("model")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>VIN</td><td style='padding:6px;'>"+testCarMap.get("vin")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Pick-up</td><td style='padding:6px;'>"+testCarMap.get("pickUpTime")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Drop-off</td><td style='padding:6px;'>"+testCarMap.get("dropOffTime")+"</td></tr></table><hr/><p>Thank you for choosing FCR Inc!</p></div>",
                MailController.buildHtml(firstName, userId, paymentId, reservationIds1, carsN), "Mail Controller Build HTML does not match with param types {reservationIds1, carsN}"),
            () -> assertEquals("<div style='font-family: sans-serif; max-width: 600px; margin: auto;'><h2>Reservation Confirmed</h2><p>Hi "+firstName+",</p><p>Your reservation is confirmed. Here are your booking details:</p><table style='width:100%; margin-bottom:16px;'><tr><td style='padding:6px; font-weight:bold;'>User ID</td><td style='padding:6px;'>"+userId+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Payment Reference</td><td style='padding:6px;'>"+paymentId+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Reservation ID(s)</td><td style='padding:6px;'>111, 222</td></tr></table><hr/><table style='width:100%; border-collapse: collapse; margin-bottom: 16px;'><tr><td style='padding:6px; font-weight:bold;'>Vehicle</td><td style='padding:6px;'>"+testCarMap.get("year")+" "+testCarMap.get("make")+" "+testCarMap.get("model")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>VIN</td><td style='padding:6px;'>"+testCarMap.get("vin")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Pick-up</td><td style='padding:6px;'>"+testCarMap.get("pickUpTime")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Drop-off</td><td style='padding:6px;'>"+testCarMap.get("dropOffTime")+"</td></tr></table><hr/><table style='width:100%; border-collapse: collapse; margin-bottom: 16px;'><tr><td style='padding:6px; font-weight:bold;'>Vehicle</td><td style='padding:6px;'>"+testCarMap.get("year")+" "+testCarMap.get("make")+" "+testCarMap.get("model")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>VIN</td><td style='padding:6px;'>"+testCarMap.get("vin")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Pick-up</td><td style='padding:6px;'>"+testCarMap.get("pickUpTime")+"</td></tr><tr><td style='padding:6px; font-weight:bold;'>Drop-off</td><td style='padding:6px;'>"+testCarMap.get("dropOffTime")+"</td></tr></table><hr/><p>Thank you for choosing FCR Inc!</p></div>",
                MailController.buildHtml(firstName, userId, paymentId, reservationIdsN, carsN), "Mail Controller Build HTML does not match with param types {reservationIdsN, carsN}")
        );


    }

}